#!/usr/bin/env bash

[ -f ~/.screenlayout/archdev.sh ] && source ~/.screenlayout/archdev.sh &
# Initialize PATH Variable

$HOME/.config/polybar/launch.sh &
$HOME/.local/bin/openweatherwidget -refresh &
sxhkd &
dunst &
xautolock -time 10 -locker ~/.scripts/locker &
$HOME/.scripts/bspwm_subscribe_sticky &
$HOME/.scripts/bspwm_subscribe_hidden &
picom &
xbanish &
nitrogen --restore &
start-pulseaudio-x11 &
volumeicon &

killall -q volumeicon

while pgrep -u $UID -x volumeicon >/dev/null; do sleep 1; done

command -v volumeicon > /dev/null && volumeicon &

killall -q blueman-applet
while pgrep -u $UID -x blueman-applet >/dev/null; do sleep 1; done

command -v blueman-applet > /dev/null && blueman-applet &

killall -q nm-applet
while pgrep -u $UID -x nm-applet >/dev/null; do sleep 1; done

command -v nm-applet > /dev/null && nm-applet &

killall -q udiskie
while pgrep -u $UID -x udiskie >/dev/null; do sleep 1; done

command -v udiskie > /dev/null && udiskie -t -n &
#bspwm initial config section

bspc rule -r "*"

${HOME}/.config/bspwm/setmonitor.sh

bspc desktop -f 1

# source the colors.
. "${HOME}/.bord-themes.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

bspc config border_width            1
bspc config window_gap              0
bspc config top_padding             20
bspc config bottom_padding          0
bspc config right_padding           0
bspc config left_padding            0
bspc config focus_follows_pointer   false
bspc config single_monocle         true

#bspc config external_rules_command ${HOME}/.scripts/bspwm_external_rules
bspc config automatic_scheme longest_side 
bspc config initial_polarity second_child

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a XClock state=floating
bspc rule -a Snap-store state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zenity state=floating
bspc rule -a openfortiGUI state=floating
bspc rule -a xpad state=floating
bspc rule -a Yad state=floating
bspc rule -a vlc state=floating
bspc rule -a "Microsoft Teams - Preview" state=floating
bspc rule -a mpv state=floating
bspc rule -a GitKraken state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
