#!/usr/bin/env bash

# Initialize PATH Variable

. "${HOME}/.pathdef"


#AUTOSTART section
. "${HOME}/.xcommonstart"

$HOME/.config/polybar/launch.sh &
sxhkd &


#bspwm initial config section

bspc rule -r "*"

${HOME}/.config/bspwm/setmonitor.sh

bspc desktop -f 1

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

bspc config border_width            1
bspc config window_gap              0
bspc config top_padding             -4
bspc config bottom_padding          0
bspc config right_padding           0
bspc config left_padding            0
bspc config focus_follows_pointer   true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a XClock state=floating
bspc rule -a Snap-store state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zenity state=floating
bspc rule -a openfortiGUI state=floating
bspc rule -a xpad state=floating
