#! /bin/sh

bspc rule -r "*"

nitrogen --restore &

set_current_city 1 &

#map CapsLock to Escape key
setxkbmap -option caps:escape

dunst &
xcompmgr &

xautolock -time 10 -locker slock &

$HOME/.config/polybar/launch.sh

sxhkd &

blueman-applet &
nm-applet &
udiskie -A -t &

xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc desktop -f 1

bspc config border_width            3
bspc config focused_border_color    "#0a6cf5"
bspc config window_gap              15
bspc config top_padding             0
bspc config bottom_padding          0
bspc config right_padding           0
bspc config left_padding            0
bspc config focus_follows_pointer   true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
