#!/usr/bin/env bash


PADDING=$(bspc config top_padding)

if [[ "$PADDING" == "0" ]]; then
    polybar-msg cmd show ; bspc config top_padding 20
else
    polybar-msg cmd hide ; bspc config top_padding 0
fi
