#!/usr/bin/env bash

source "$HOME/.pathdef"

#source "$HOME/.cache/wal/colors.sh"
source "$HOME/.scripts/nord-colors.sh"

dmenu_path | dmenu -nb $background -nf $foreground -sb $color4 -sf $foreground -nsb $background -nsf $color3 -ssb $color4 -ssf $color3 "$@" | ${SHELL-:"/bin/sh"} &
