#!/usr/bin/env bash

$BROWSER --new-window \
    https://www.icv-crew.com/forum/index.php?board=102.0 \
    http://ddunlimited.net/viewforum.php?f=324 \
    https://ilcorsaronero.pw/cat/1 \
    http://umbesrv:32400/ \
    http://umbesrv:18080/ &
