#!/usr/bin/env sh

CITY=$(current_city) &&
    NEW_CITY=$(zenity --entry \
    --title="Current City" \
    --text="Enter current city" \
    --entry-text=$CITY 2> /dev/null) &&
    set_current_city $NEW_CITY ;
    polybar_weather 1 > /dev/null
