#!/usr/bin/env sh

BASE_PATH=$HOME/.scripts
CITY=$($BASE_PATH/current_city) &&
    NEW_CITY=$(zenity --entry \
    --title="Current City" \
    --text="Enter current city" \
    --entry-text=$CITY 2> /dev/null) &&
    set_current_city $NEW_CITY ;
    $BASE_PATH/polybar_weather 1 > /dev/null
