#!/usr/bin/env bash

REFRESH=$1

CURRENT_CITY_PATH=$HOME/.cache/umbe/current_city
CURRENT_CITY_DIR=$(dirname "$CURRENT_CITY_PATH")

[ ! -d $CURRENT_CITY_DIR  ] && 
    mkdir -p $CURRENT_CITY_DIR
[ ! -f $CURRENT_CITY_PATH ] &&
    touch $CURRENT_CITY_PATH &&
    NEW="1"

[[ $NEW = "1" || $REFRESH = "1" ]] &&
    curl -s https://ipinfo.io | jq -r '.city' > $CURRENT_CITY_PATH

[[ -n "$REFRESH" && $REFRESH != "1" ]] &&
    echo -n "$REFRESH" > $CURRENT_CITY_PATH
